name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - name: Install CocoaPods
        run: pod install --repo-update

      - name: Build with xcodebuild
        run: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' build

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4' # Especifica la versión de Xcode que tienes instalada

      - name: Build the app
        run: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' build
      - name: Build iOS Framework
        run: ./gradlew :shared:packForXcode -Pmode=DEBUG -PsdkName=iphonesimulator

      - name: Build iOS App
        run: |
          xcodebuild -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/*.ipa
