name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode_12.4.app

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Build iOS Framework
        run: ./gradlew :shared:packForXcode -Pmode=DEBUG -PsdkName=iphonesimulator

      - name: Build iOS App
        run: |
          xcodebuild -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/YourApp.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/YourApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/*.ipa
