name: Build iOS Framework

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build iOS Framework
        run: ./gradlew :shared:packForXcode -Pmode=DEBUG -PsdkName=iphonesimulator
        
      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Upload iOS Framework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: shared/build/xcode-frameworks
