name: Create .xcworkspace

on:
  workflow_dispatch:

jobs:
  create-xcworkspace:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .xcworkspace
        run: |
          mkdir -p MyApp
          cd MyApp
          xcodebuild -create-xcworkspace -scheme MyAppScheme # Ajusta el nombre del esquema a tu proyecto
          cd ..
          mv MyApp/MyApp.xcworkspace ./MyApp.xcworkspace

      - name: Commit and Push .xcworkspace
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Add .xcworkspace'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}